### ISSUE TITLE
Suppress unknown entity errors & issue with missing sensor?

### ISSUE THREAD

**Issue by gcoan** [Tomer27cz/energy-line-gauge#8]
Firstly thanks for all the changes I see you have been making to the line gauge, lots of configurability.

I have identified two odd things.

Firstly one of my entity sensors has gone unknown, probably lost connection to the wifi, and this rather messes up the line gauge.  Wonder if it could/should be suppressed?
![image](https://github.com/user-attachments/assets/713c8efe-1058-420f-8138-57f89a6c7b11)

Secondly, I think there is a rounding error somewhere.  As you can see Extension Power is only showing the fridge as consuming any power, but in fact from the bar graph above the dishwasher is as well:
![image](https://github.com/user-attachments/assets/981af622-8548-4e31-ac52-2145e9eb7e53)
![image](https://github.com/user-attachments/assets/1b41b9af-6cc3-41f7-8947-1c30b8d0db3a)

Both Fridge Power and Dishwasher Power are configured as children of Extension Power:

```
type: custom:energy-line-gauge
min: 0
entities:
  - entity: sensor.toby_bedroom_light_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.toby_bedroom_sockets_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.cooker_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.kettle_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.dishwasher_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.tumble_dryer_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.fridge_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.horse_shed_heater_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
  - entity: sensor.workshop_heater_power
    color: auto
    state_content:
      - name
    multiplier: 1
    unit: kW
cutoff: 0.1
corner: lite_rounded
position: left
line_text_position: left
line_text_size: 1
color:
  - 223
  - 238
  - 212
color_bg:
  - 229
  - 229
  - 229
untracked_legend: false
untracked_state_content:
  - name
legend_hide: false
legend_all: false
show_delta: false
entity: sensor.extension_power
unit: kW
precision: 1
subtitle: Extension Power
```
